name: Build and Test

on:
  push:
    branches: [main, dev]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'benchmarks/**'
      - 'tools/**'
      - '*.sln'
      - '*.props'
      - 'global.json'
      - '.github/workflows/build-and-test.yml'
  pull_request:
    branches: [main, dev]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'benchmarks/**'
      - 'tools/**'
      - '*.sln'
      - '*.props'
      - 'global.json'
      - '.github/workflows/build-and-test.yml'

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: Restore dependencies
      run: dotnet restore ./Light.GuardClauses.sln
    - name: Build
      run: dotnet build ./Light.GuardClauses.sln -c Release --no-restore
    - name: Test
      run: dotnet test ./Light.GuardClauses.sln -c Release --no-build --verbosity normal
